export const START_ADD_BUS_ASYNC = 'START_ADD_BUS_ASYNC';
export const START_ADD_BUS = 'START_ADD_BUS';
export const ADD_BUS_SUCCESS = 'ADD_BUS_SUCCESS';
export const ADD_BUS_FAIL = 'ADD_BUS_FAIL';

export const START_AUTH_ASYNC = 'START_AUTH_ASYNC';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_RESULTS_START_ASYNC = 'FETCH_RESULTS_START_ASYNC';
export const FETCH_RESULTS_START = 'FETCH_RESULTS_START';
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';
export const FETCH_RESULTS_FAIL = 'FETCH_RESULTS_FAIL';

export const FETCH_SEARCH_START = 'FETCH_SEARCH_RESULTS_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const SELECT_BUS = 'SELECT_BUS';

export const UPDATE_SEAT_SELECTED = 'UPDATE_SEAT_SELECTED';

export const FETCH_TRIP_ASYNC = 'FETCH_TRIP_ASYNC';
export const FETCH_TRIP_START = 'FETCH_TRIP_START';
export const FETCH_TRIP_SUCCESS = 'FETCH_TRIP_SUCCESS';
export const FETCH_TRIP_FAIL = 'FETCH_TRIP_FAIL';

export const BOOK_TICKET_ASYNC = 'BOOK_TICKET_ASYNC';
export const BOOK_TICKET_START = 'BOOK_TICKET_START';
export const BOOK_TICKET_SUCCESS = 'BOOK_TICKET_SUCCESS';
export const BOOK_TICKET_FAIL = 'BOOK_TICKET_FAIL';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const CLEAR_BOOK_TICKET = 'CLEAR_BOOK_TICKET';

export const FETCH_TICKETS_ASYNC = 'FETCH_TICKETS_ASYNC';
export const FETCH_TICKETS_START = 'FETCH_TICKETS_START';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAIL = 'FETCH_TICKETS_FAIL';

export const CANCEL_TICKET_ASYNC = 'CANCEL_TICKET_ASYNC';
export const CANCEL_TICKET_START = 'CANCEL_TICKET_START';
export const CANCEL_TICKET_SUCCESS = 'CANCEL_TICKET_SUCCESS';
export const CANCEL_TICKET_FAIL = 'CANCEL_TICKET_FAIL';

export const SEND_EMAIL_ALERT_START = 'SEND_EMAIL_ALERT_START';
export const SEND_EMAIL_ALERT_ASYNC = 'SEND_EMAIL_ALERT_ASYNC';
export const SEND_EMAIL_ALERT_SUCCESS = 'SEND_EMAIL_ALERT_SUCCESS';
export const SEND_EMAIL_ALERT_FAIL = 'SEND_EMAIL_ALERT_FAIL';


export const FETCH_TRIPS_ASYNC = 'FETCH_TRIPS_ASYNC';
export const FETCH_TRIPS_START = 'FETCH_TRIPS_START';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIPS_FAIL = 'FETCH_TRIPS_FAIL';

export const ENABLE_CHAT_ASYNC = 'ENABLE_CHAT_ASYNC';
export const ENABLE_CHAT_START = 'ENABLE_CHAT_START';
export const ENABLE_CHAT_SUCCESS = 'ENABLE_CHAT_SUCCESS';
export const ENABLE_CHAT_FAIL = 'ENABLE_CHAT_FAIL';